### ISSUE TITLE
Could you please share the data of CASIA NIR-VIS2.0?

### ISSUE THREAD

**Issue by addiajsjjs** [AmitCohen3/Accessorize-in-the-dark#1]
Could you please share the data of CASIA NIR-VIS2.0?

**Comment by mahmoods01** [comment]
As we don't own the dataset, we don't have the rights to publish it here. Please consider obtaining it from the original authors, per the instructions in the following link.

http://www.cbsr.ia.ac.cn/english/NIR-VIS-2.0-Database.html

**Comment by addiajsjjs** [comment]
Thanks for your reply, but my CASIA NIR-VIS2.0 data set is arranged like this: , 
**CASIA NIR-VIS 2.0
   -NIR
    --s1_NIR_00001_001.bmp
    --s1_NIR_00001_002.bmp
    -- ....
   -VIS
     --s1_VIS_00001_001.jpg
     --s1_VIS_00001_002.jpg
     -- ....
   -protocols**
and I don’t have **vis_eyes.txt** and **nir_eyes.txt**. I would like to ask you if I have overlooked any processing steps? Or is there something wrong with my dataset?
